```yaml
name: Compile JSON to SRS

on:
  push:
    paths:
      - "singbox/v1.12.0/*.json"   # 👈 监控这个路径下的 json 文件
  workflow_dispatch:               # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 👈 允许提交回仓库

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest sing-box version
        id: get_version
        run: |
          LATEST=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep tag_name | cut -d '"' -f4)
          echo "LATEST_VERSION=$LATEST" >> $GITHUB_ENV

      - name: Install Sing-box
        run: |
          echo "Downloading sing-box $LATEST_VERSION"
          curl -fsSL "https://github.com/SagerNet/sing-box/releases/download/$LATEST_VERSION/sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz" -o sing-box.tar.gz
          tar -xzf sing-box.tar.gz
          sudo mv sing-box-*/sing-box /usr/local/bin/

      - name: Compile JSON to SRS
        run: |
          shopt -s nullglob
          for f in singbox/v1.12.0/*.json; do
            name=$(basename "$f" .json)
            echo "Compiling $f -> singbox/v1.12.0/$name.srs"
            sing-box rule-set compile "$f" "singbox/v1.12.0/$name.srs"
          done

      - name: Commit and push SRS files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add singbox/v1.12.0/*.srs
          git commit -m "Auto compile SRS from JSON (sing-box $LATEST_VERSION) [skip ci]" || echo "No changes to commit"
          git push
```
