name: Convert JSON to SRS

on:
  workflow_dispatch:   # 手动触发
  push:
    paths:
      - "singbox/*"      # 仅 singbox 目录下的文件（不含子目录）
  schedule:
    - cron: "0 4 * * *"  # 每天 04:00 UTC 自动运行（北京时间中午 12:00）

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # 需要完整 git 历史来做 diff

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Install sing-box
        run: |
          RELEASE_JSON=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest)
          TAG=$(echo "$RELEASE_JSON" | jq -r .tag_name)
          echo "Latest tag: $TAG"

          ARCH=$(uname -m)
          case "$ARCH" in
            x86_64) KEYWORD="amd64" ;;
            aarch64|arm64) KEYWORD="arm64" ;;
            i386|i686) KEYWORD="386" ;;
            *) KEYWORD="amd64" ;;
          esac

          DOWNLOAD_URL=$(echo "$RELEASE_JSON" | jq -r --arg KEYWORD "$KEYWORD" '.assets[] | select(.name | test("linux.*" + $KEYWORD)) | .browser_download_url' | head -n1)

          if [ -z "$DOWNLOAD_URL" ]; then
            echo "No matching asset found for arch $ARCH"
            exit 1
          fi

          echo "Downloading from $DOWNLOAD_URL"
          curl -sL "$DOWNLOAD_URL" -o sing-box.tar.gz

          ls -lh sing-box.tar.gz
          file sing-box.tar.gz

          tar -xzf sing-box.tar.gz
          sudo mv sing-box*/sing-box /usr/local/bin/

      - name: Find changed JSON files
        id: changes
        run: |
          CHANGED=$(git diff --name-only HEAD~1 HEAD | grep '^singbox/.*\.json$' || true)
          echo "changed=$CHANGED" >> $GITHUB_OUTPUT

      - name: Convert JSON -> SRS
        if: steps.changes.outputs.changed != ''
        run: |
          for file in ${{ steps.changes.outputs.changed }}; do
            [ -f "$file" ] || continue
            out="${file%.json}.srs"
            echo "Converting $file -> $out"
            sing-box rule-set compile --output "$out" "$file"
          done

      - name: Commit converted files
        if: steps.changes.outputs.changed != ''
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto convert updated JSON rules to SRS"
          file_pattern: singbox/*.srs
