name: Convert JSON to SRS

on:
  workflow_dispatch:
  push:
    paths:
      - "singbox/*"
  schedule:
    - cron: "0 4 * * *"  # 每天 04:00 UTC 自动运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Install sing-box
        run: |
          RELEASE_JSON=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest)
          TAG=$(echo "$RELEASE_JSON" | jq -r .tag_name)
          echo "Latest tag: $TAG"

          ARCH=$(uname -m)
          case "$ARCH" in
            x86_64) KEYWORD="amd64" ;;
            aarch64|arm64) KEYWORD="arm64" ;;
            i386|i686) KEYWORD="386" ;;
            *) KEYWORD="amd64" ;;
          esac

          DOWNLOAD_URL=$(echo "$RELEASE_JSON" | jq -r --arg KEYWORD "$KEYWORD" '.assets[] | select(.name | test("linux.*" + $KEYWORD)) | .browser_download_url' | head -n1)

          if [ -z "$DOWNLOAD_URL" ]; then
            echo "No matching asset found for arch $ARCH"
            exit 1
          fi

          echo "Downloading from $DOWNLOAD_URL"
          curl -sL "$DOWNLOAD_URL" -o sing-box.tar.gz

          tar -xzf sing-box.tar.gz
          sudo mv sing-box*/sing-box /usr/local/bin/

      - name: Find changed JSON files
        id: changes
        run: |
          CHANGED=$(git diff --name-only HEAD~1 HEAD | grep '^singbox/.*\.json$' || true)
          echo "changed=$CHANGED" >> $GITHUB_OUTPUT

      - name: Convert JSON -> SRS
        run: |
          if [ -z "${{ steps.changes.outputs.changed }}" ]; then
            echo "No changed JSON detected, converting all JSON files"
            FILES=$(ls singbox/*.json 2>/dev/null || true)
          else
            FILES=${{ steps.changes.outputs.changed }}
          fi

          for file in $FILES; do
            [ -f "$file" ] || continue
            out="${file%.json}.srs"
            echo "Converting $file -> $out"
            sing-box rule-set compile --output "$out" "$file"
          done

      - name: Commit converted files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add singbox/*.srs
          git diff --quiet && echo "No changes to commit" || git commit -m "Auto convert JSON rules to SRS" && git push
